name: bids23
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.11
 - numpy
 - gdal==3.7.2
 - pyproj
 - pandas
 - geopandas
 - rasterio
 - scipy
 - pystac-client
 - matplotlib
 - xarray
 - rioxarray
 - tqdm
 - folium
 - mapclassify
 - pip
 - pytorch
 - seaborn
 - matplotlib
 - requests
 - tqdm
 - scikit-learn
 - netCDF4
 - torchvision
 - xgboost
 - pip:
    - earthdaily
