name: bids23
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.11
 - numpy
 - gdal==3.7.2
 - pyproj
 - pandas
 - geopandas
 - rasterio
 - scipy
 - pystac-client
 - requests
 - matplotlib
 - xarray
 - rioxarray
 - netcdf4
 - pystac
 - stackstac
 - odc-stac
 - tqdm
 - joblib
 - pip
 - pytorch
 - seaborn
 - matplotlib
 - requests
 - visdom
 - tqdm
 - scikit-learn
 - jupyter
 - netCDF4
 - visdom
 - torchvision
 - spyder
 - xgboost
 - jupyter
 - contextily
 - pip:
    - earthdaily
